import path from "node:path";
import { adapterRegistry, deriveAdapterSupport } from "./adapter-registry.js";
import type { AgentId, Recipe, SupportStatus } from "./schema.js";

export type GeneratedAdapterFileRole =
  | "entrypoint"
  | "checklist"
  | "example-input"
  | "example-output"
  | "metadata"
  | "output-schema"
  | "policy";

export interface GeneratedAdapterFile {
  path: string;
  content: string;
  role: GeneratedAdapterFileRole;
}

export interface AdapterInvocation {
  mode: "manual" | "implicit";
  command: string | null;
  implicitInvocationControl: "enforced" | "not-supported" | "unknown";
  warning: string | null;
}

export interface GeneratedAdapterBundle {
  entrypoint: string;
  files: GeneratedAdapterFile[];
  invocation: AdapterInvocation;
}

export interface RecipeBundleSources {
  workflow: string;
  checklist: string;
  exampleInput: string;
  exampleOutput: string;
  metadata: string;
  outputSchema: string;
}

export type RecipeBundleSource = keyof RecipeBundleSources;

export interface UnsafeAdapterInterpolation {
  agent: Extract<AgentId, "claude-code" | "gemini-cli" | "opencode">;
  syntax: "!{...}" | "@{...}" | "!`...`" | "@path";
  effect: "shell command substitution" | "file content substitution";
}

interface AdapterInterpolationRule extends UnsafeAdapterInterpolation {
  matches(content: string): boolean;
}

const openCodeFileReference = /(?<![A-Za-z0-9_.@-])@(?=[A-Za-z0-9_./-])/;
const adapterInterpolationRules: readonly AdapterInterpolationRule[] = [
  {
    agent: "gemini-cli",
    syntax: "!{...}",
    effect: "shell command substitution",
    matches: (content) => content.includes("!{"),
  },
  {
    agent: "gemini-cli",
    syntax: "@{...}",
    effect: "file content substitution",
    matches: (content) => content.includes("@{"),
  },
  {
    agent: "opencode",
    syntax: "!`...`",
    effect: "shell command substitution",
    matches: (content) => content.includes("!`"),
  },
  {
    agent: "opencode",
    syntax: "@path",
    effect: "file content substitution",
    matches: (content) => openCodeFileReference.test(content),
  },
  {
    agent: "claude-code",
    syntax: "!`...`",
    effect: "shell command substitution",
    matches: (content) => content.includes("!`"),
  },
];

const bundleSourceFiles: Readonly<Record<RecipeBundleSource, string>> = {
  workflow: "workflow.md",
  checklist: "checklist.md",
  exampleInput: "examples/input.md",
  exampleOutput: "examples/expected-output.md",
  metadata: "recipe.yml",
  outputSchema: "output.schema.json",
};

export function findUnsafeAdapterInterpolations(
  content: string,
  source: RecipeBundleSource,
  agent?: AgentId,
): UnsafeAdapterInterpolation[] {
  return adapterInterpolationRules
    .filter(
      (rule) =>
        (agent === undefined || rule.agent === agent) &&
        // OpenCode expands @path only while parsing the command template. Auxiliary bundle files
        // remain inert assets, where @scope/package and similar evidence are ordinary content.
        (rule.syntax !== "@path" || source === "workflow") &&
        rule.matches(content),
    )
    .map(({ agent: affectedAgent, syntax, effect }) => ({
      agent: affectedAgent,
      syntax,
      effect,
    }));
}

function assertSafeAdapterSources(agent: AgentId, sources: RecipeBundleSources): void {
  for (const [source, content] of Object.entries(sources) as Array<[RecipeBundleSource, string]>) {
    for (const violation of findUnsafeAdapterInterpolations(content, source, agent)) {
      throw new Error(
        `Cannot generate the ${agent} adapter because ${bundleSourceFiles[source]} contains ${violation.syntax}, which the consumer interprets as ${violation.effect}. Recipe bundle content must remain inert.`,
      );
    }
  }
}

interface AdapterLayout {
  entrypoint(recipe: Recipe): string;
  asset(recipe: Recipe, relative: string): string;
}

export interface Adapter {
  id: AgentId;
  version: string;
  displayName: string;
  support: SupportStatus;
  exportFormat:
    | "plain-markdown-bundle"
    | "skill-md-bundle"
    | "custom-command-toml-bundle"
    | "opencode-command-markdown-bundle";
  destinationPattern: string;
  namingRules: string;
  officialDocumentation: string | null;
  formatConfirmed: boolean;
  exporterImplemented: boolean;
  entrypoint(recipe: Recipe): string;
  invocation(recipe: Recipe): AdapterInvocation;
  generate(recipe: Recipe, sources: RecipeBundleSources): GeneratedAdapterBundle;
  assumptions: string;
  limitations: string;
}

const generatedHeader = (recipe: Recipe) =>
  `Generated by Agentic Workflows.\nSource recipe: ${recipe.id}\nRecipe version: ${recipe.version}\nDo not edit managed files directly unless you intend to replace this installation manually.\n\n`;

function bundleLinks(entrypoint: string, layout: AdapterLayout, recipe: Recipe) {
  const directory = path.posix.dirname(entrypoint);
  const relative = (target: string) =>
    path.posix.relative(directory, target) || path.posix.basename(target);
  return {
    checklist: relative(layout.asset(recipe, "checklist.md")),
    exampleInput: relative(layout.asset(recipe, "examples/input.md")),
    exampleOutput: relative(layout.asset(recipe, "examples/expected-output.md")),
    metadata: relative(layout.asset(recipe, "recipe.yml")),
    outputSchema: relative(layout.asset(recipe, "output.schema.json")),
  };
}

function workflowWithBundleLinks(
  recipe: Recipe,
  sources: RecipeBundleSources,
  layout: AdapterLayout,
): string {
  const entrypoint = layout.entrypoint(recipe);
  const links = bundleLinks(entrypoint, layout, recipe);
  const workflow = sources.workflow
    .replaceAll(/(?:\.\/)?examples\/input\.md/g, links.exampleInput)
    .replaceAll(/(?:\.\/)?examples\/expected-output\.md/g, links.exampleOutput);
  return `${generatedHeader(recipe)}${workflow.trimEnd()}\n\n## Installed bundle resources\n\n- [Execution checklist](${links.checklist})\n- [Complete example input](${links.exampleInput})\n- [Complete expected output](${links.exampleOutput})\n- [Recipe metadata](${links.metadata})\n- [Output contract](${links.outputSchema})\n`;
}

function bundleFiles(
  recipe: Recipe,
  sources: RecipeBundleSources,
  layout: AdapterLayout,
  entrypointContent: string,
): GeneratedAdapterFile[] {
  return [
    { path: layout.entrypoint(recipe), content: entrypointContent, role: "entrypoint" },
    {
      path: layout.asset(recipe, "checklist.md"),
      content: sources.checklist,
      role: "checklist",
    },
    {
      path: layout.asset(recipe, "examples/input.md"),
      content: sources.exampleInput,
      role: "example-input",
    },
    {
      path: layout.asset(recipe, "examples/expected-output.md"),
      content: sources.exampleOutput,
      role: "example-output",
    },
    {
      path: layout.asset(recipe, "recipe.yml"),
      content: sources.metadata,
      role: "metadata",
    },
    {
      path: layout.asset(recipe, "output.schema.json"),
      content: sources.outputSchema,
      role: "output-schema",
    },
  ];
}

const explicitInvocation =
  (command: (recipe: Recipe) => string | null): Adapter["invocation"] =>
  (recipe) => ({
    mode: "manual",
    command: command(recipe),
    implicitInvocationControl: "not-supported",
    warning:
      "Invoke this workflow explicitly. Declared approval gates remain advisory and are not satisfied by CLI confirmation.",
  });

function markdownAdapter(options: {
  id: AgentId;
  layout: AdapterLayout;
  invocation: Adapter["invocation"];
  frontmatter?: (recipe: Recipe) => string;
  suffix?: string;
  additionalFiles?: (recipe: Recipe, sources: RecipeBundleSources) => GeneratedAdapterFile[];
  limitations?: string;
}): Adapter {
  const registry = adapterRegistry[options.id];
  return {
    id: options.id,
    version: registry.version,
    displayName: registry.displayName,
    support: deriveAdapterSupport(registry),
    exportFormat: registry.exportFormat,
    destinationPattern: registry.destinationPattern,
    namingRules: registry.namingRules,
    officialDocumentation: registry.officialDocumentation,
    formatConfirmed: registry.formatConfirmed,
    exporterImplemented: registry.exporterImplemented,
    entrypoint: options.layout.entrypoint,
    invocation: options.invocation,
    generate: (recipe, sources) => {
      assertSafeAdapterSources(options.id, sources);
      const body = workflowWithBundleLinks(recipe, sources, options.layout);
      const entrypointContent = `${options.frontmatter?.(recipe) ?? ""}${body}${options.suffix ?? ""}`;
      return {
        entrypoint: options.layout.entrypoint(recipe),
        files: [
          ...bundleFiles(recipe, sources, options.layout, entrypointContent),
          ...(options.additionalFiles?.(recipe, sources) ?? []),
        ],
        invocation: options.invocation(recipe),
      };
    },
    assumptions: "Project-local bundle using the documented current format.",
    limitations:
      options.limitations ??
      "Export generation and local installation are independent from external agent execution.",
  };
}

const directoryLayout = (
  root: (recipe: Recipe) => string,
  entrypointName: string,
): AdapterLayout => ({
  entrypoint: (recipe) => path.posix.join(root(recipe), entrypointName),
  asset: (recipe, relative) => path.posix.join(root(recipe), relative),
});

const adjacentAssetsLayout = (
  entrypoint: (recipe: Recipe) => string,
  assetsRoot: (recipe: Recipe) => string,
): AdapterLayout => ({
  entrypoint,
  asset: (recipe, relative) => path.posix.join(assetsRoot(recipe), relative),
});

const genericLayout = directoryLayout(
  (recipe) => `.agentic-workflows/workflows/${recipe.id}`,
  "workflow.md",
);
const claudeLayout = directoryLayout((recipe) => `.claude/skills/${recipe.id}`, "SKILL.md");
const codexLayout = directoryLayout((recipe) => `.agents/skills/${recipe.id}`, "SKILL.md");
const cursorLayout = directoryLayout((recipe) => `.cursor/skills/${recipe.id}`, "SKILL.md");
const geminiLayout = adjacentAssetsLayout(
  (recipe) => `.gemini/commands/${recipe.id}.toml`,
  (recipe) => `.gemini/commands/${recipe.id}.assets`,
);
const openCodeLayout = adjacentAssetsLayout(
  (recipe) => `.opencode/commands/${recipe.id}.md`,
  (recipe) => `.opencode/commands/${recipe.id}.assets`,
);

export const adapters: Readonly<Record<AgentId, Adapter>> = {
  generic: markdownAdapter({
    id: "generic",
    layout: genericLayout,
    invocation: explicitInvocation(() => null),
  }),
  cursor: markdownAdapter({
    id: "cursor",
    layout: cursorLayout,
    invocation: (recipe) => ({
      mode: "manual",
      command: `/${recipe.id}`,
      implicitInvocationControl: "enforced",
      warning:
        "Model invocation is disabled. Invoke this workflow explicitly; declared approval gates remain advisory.",
    }),
    frontmatter: (recipe) =>
      `---\nname: ${recipe.id}\ndescription: ${JSON.stringify(recipe.summary)}\ndisable-model-invocation: true\n---\n\n`,
    limitations: "Agent Skill export uses Cursor's project-local skill discovery path.",
  }),
  "gemini-cli": {
    id: "gemini-cli",
    version: adapterRegistry["gemini-cli"].version,
    displayName: adapterRegistry["gemini-cli"].displayName,
    support: deriveAdapterSupport(adapterRegistry["gemini-cli"]),
    exportFormat: adapterRegistry["gemini-cli"].exportFormat,
    destinationPattern: adapterRegistry["gemini-cli"].destinationPattern,
    namingRules: adapterRegistry["gemini-cli"].namingRules,
    officialDocumentation: adapterRegistry["gemini-cli"].officialDocumentation,
    formatConfirmed: adapterRegistry["gemini-cli"].formatConfirmed,
    exporterImplemented: adapterRegistry["gemini-cli"].exporterImplemented,
    entrypoint: geminiLayout.entrypoint,
    invocation: explicitInvocation((recipe) => `/${recipe.id}`),
    generate: (recipe, sources) => {
      assertSafeAdapterSources("gemini-cli", sources);
      const prompt = workflowWithBundleLinks(recipe, sources, geminiLayout);
      const content = `description = ${JSON.stringify(recipe.summary)}\nprompt = ${JSON.stringify(`${prompt}\nUser input: {{args}}`)}\n`;
      return {
        entrypoint: geminiLayout.entrypoint(recipe),
        files: bundleFiles(recipe, sources, geminiLayout, content),
        invocation: explicitInvocation((value) => `/${value.id}`)(recipe),
      };
    },
    assumptions: "Gemini CLI project custom-command TOML bundle.",
    limitations:
      "The command is explicitly invoked and does not inject shell output or external files automatically.",
  },
  opencode: markdownAdapter({
    id: "opencode",
    layout: openCodeLayout,
    invocation: explicitInvocation((recipe) => `/${recipe.id}`),
    frontmatter: (recipe) => `---\ndescription: ${JSON.stringify(recipe.summary)}\n---\n\n`,
    suffix: "\nUser input: $ARGUMENTS\n",
  }),
  "claude-code": markdownAdapter({
    id: "claude-code",
    layout: claudeLayout,
    invocation: (recipe) => ({
      mode: "manual",
      command: `/${recipe.id}`,
      implicitInvocationControl: "enforced",
      warning:
        "Model invocation is disabled. Invoke this workflow explicitly; declared approval gates remain advisory.",
    }),
    frontmatter: (recipe) =>
      `---\nname: ${recipe.id}\ndescription: ${JSON.stringify(recipe.summary)}\ndisable-model-invocation: true\n---\n\n`,
  }),
  codex: markdownAdapter({
    id: "codex",
    layout: codexLayout,
    invocation: (recipe) => ({
      mode: "manual",
      command: `$${recipe.id}`,
      implicitInvocationControl: "enforced",
      warning:
        "Implicit invocation is disabled by the installed policy. Invoke this workflow explicitly; declared approval gates remain advisory.",
    }),
    frontmatter: (recipe) =>
      `---\nname: ${recipe.id}\ndescription: ${JSON.stringify(recipe.summary)}\n---\n\n`,
    additionalFiles: (recipe) => [
      {
        path: `.agents/skills/${recipe.id}/agents/openai.yaml`,
        content: "policy:\n  allow_implicit_invocation: false\n",
        role: "policy",
      },
    ],
    limitations:
      "The policy prevents implicit invocation but does not enforce the workflow's human approval gates.",
  }),
};

export function generateAdapterBundle(
  recipe: Recipe,
  sources: RecipeBundleSources,
  agent: AgentId,
): GeneratedAdapterBundle {
  return adapters[agent].generate(recipe, sources);
}
