// Generated by scripts/generate-v022-v030-migrations.ts from v0.2.2 (8de51cb34e4494fd0b6478292027a153ea43293b) to CLI 0.3.0.
// This release-pair registry is immutable after v0.3.0 exists.

import type { AgentId } from "@kauanpolydoro/agentic-workflows-core";

export interface RetainedV2Migration {
  recipe: string;
  from_version: string;
  to_version: string;
  bundles: Record<AgentId, { from: string; to: string }>;
}

export const retainedV022ToV030Migrations = [
  {
    recipe: "api-contract-review",
    from_version: "1.2.1",
    to_version: "1.2.2",
    bundles: {
      generic: {
        from: "93c17a3ad5a130f3d05b08cdc15ad03ddebabeeb1317d2c78aa646216a80462c",
        to: "32ecc07606b5f75a3e0b2c4bad94ff843befc9e7098371e124fd4efd24f7c129",
      },
      "claude-code": {
        from: "6da8a2643bbe27ac1e9747ebc4a5d697a46b4ce3c7164dc09dafd37b195b08dc",
        to: "1e9f254e9c1107f5908be7dabd958a91e9ace9b7761e47b203aebd8e2cb5c1fe",
      },
      codex: {
        from: "f11e46fb9c042e7a34c2cf8e29c2bd5cd274ae2e5d959705478c05263b8bdbd9",
        to: "a782a7a7ce9fa31e42a368fe30b01768a2ba9419f634944320f2a8d6fecdf48b",
      },
      cursor: {
        from: "66122a75ca1f7abf854c6a5b2015d5fd20364dbceefe8232b0e43d91c60f421b",
        to: "ef0d903d50b12b1ed0c17e9017863a708c0ede96e613ca6a702d2925032a1e4b",
      },
      "gemini-cli": {
        from: "065741b31efc9f47c484fe4bfc900fb9ba9f2e98a346ca9ff3137c35b5146111",
        to: "3e4eea3026595dc6a5a63f54347c70bf136a0a37d8036894b6f178fa5be50d93",
      },
      opencode: {
        from: "0cc91b86877fe1980e2545e70b118206816349f80c2c0668016b110619b22e6e",
        to: "365d1fde8d5593f6a3d7bf322921377e3cf355635f1bbfd2606085ff7fb70c73",
      },
    },
  },
  {
    recipe: "codebase-onboarding",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "1f67dd50fe7ba46dd4dace086e7926cafc1ce8f1474cefec07ae356fc28d33f6",
        to: "97083af49303c027a9bbc563a76faece8f012167f3699f47338b390236bc6d93",
      },
      "claude-code": {
        from: "8a5be2f0eef3d883e486b8a67d47836e8bf67b734c65b65f9319df90bdcb5fb1",
        to: "8e0bfba35015bdd6fe855e4e9ed81855bcf4696b84bea4fd1aed5f83e5023772",
      },
      codex: {
        from: "190f435a9cd6cc9739c077fc1b76a06138e73d1eec6c270561f03f8036130a8a",
        to: "3f006fd1261a8dd53e94139b9a6cee0a4a4a82c871f7953e6ef6a62c7d7d35c8",
      },
      cursor: {
        from: "9e9c8465636c6b487e4f7d50fe3c261b426c0c4063120066345d4f5fa82e4ba4",
        to: "afbc725a9506f374682c8090b6f5c9cd58739e43b9c9995f1199209d22ded215",
      },
      "gemini-cli": {
        from: "fcd34ea59d450fca3248a9588cb59ec4cd332e727f248e57d33da94f992c67de",
        to: "9e344a704d70ad2e05a68bb90a363af2cfb19ea991b600557652fbb1c2b80b1b",
      },
      opencode: {
        from: "fb94ce85214feb6ead6e8186314c0a8996013b9f5f1ddba8a70468567b86a192",
        to: "cbd5a5acdde55a1189574c254afee0f8006d498ec6fb8dcfa717569a220f0159",
      },
    },
  },
  {
    recipe: "database-migration-review",
    from_version: "1.2.1",
    to_version: "1.2.2",
    bundles: {
      generic: {
        from: "05eee41227681cd9818e61f52bcc6dfde62698a9f1634a068b6b6ce2aafff7da",
        to: "fa57a48c71117173b131d6e0ce472f0dfdb83f9b68a96fe27f7f383b8059eb35",
      },
      "claude-code": {
        from: "1aacb5e852564002c26365eabc6805a2bcf22a9aa39b8a83cf34f4e65a1c122b",
        to: "d2eff467265550675df4cdf69e9846a8fba9e94520129c539a20d4c41b905652",
      },
      codex: {
        from: "c14df7d10a7ac797a8dc61dbf9839cd7b35cd9d3b08cbaf39232d84893246334",
        to: "42a7b95c9bff997e4b243d66a21d7e2e19a6b769ca11579f1d4043fcd8cbc689",
      },
      cursor: {
        from: "e6db1a5d34a4939518afd4704eadb2d5b1c6aed27faff5d35a00e3885456a1d8",
        to: "611133d9486e64c2c8598b75dc19790cd0a3776eda0f872c94b5e39147c32aec",
      },
      "gemini-cli": {
        from: "9910a223130ae9dddadfa582cc2e397676122063cb2b610b328905f57ff3d5d8",
        to: "ae0e3f46706ccbcc0f15af2a8321c9c779c5fe391831649f104c05cf12696bc6",
      },
      opencode: {
        from: "6e96c4bc83bea901686b1d64c9557498b090937a8fabfa3fc32ca695d4c2d7af",
        to: "068c081a11b97b97fd46555c385c7ad6801ed3ebc3e03e73982082be101604ba",
      },
    },
  },
  {
    recipe: "debug-failing-ci",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "8bcb4e8b1638142e80591bf1548b897a8b99fad55f7a685987adf1b6a8c78b20",
        to: "294e05b2fdf319086b870760846ed0ec3594da3f04f092df724f2cc39843a1ff",
      },
      "claude-code": {
        from: "42e6e83a6670cce2cbbbaf3852a95c82231e3c25b17de673bee1c1969bad00b5",
        to: "38861610bfcff4bd172ad859023c552017bde2e42fcd053102c04ceac15e6291",
      },
      codex: {
        from: "2ba98bbae31271c1afe1fec3b135daad397bcf8bbf1f49f6a04da8b4ee461a11",
        to: "6a647135765377e5e691dbe718a047dbfc61e085863a2c691114583cd55c2314",
      },
      cursor: {
        from: "f7fb2aaaa103ee55d284123c1cb10478c102acbb73aa2fff9dd18f275c4b60da",
        to: "d74ceb840533b823838cacb7a8a34541d366141cc5f2f05d11f6cf732fc387d6",
      },
      "gemini-cli": {
        from: "402280539ab937ba20c83070b0959c1caa21ea699fb6da4abe8c9892ddd0a7ef",
        to: "70efac735c2fcce768f588bde5b62856125b37e9adcb028648e37c5c63657987",
      },
      opencode: {
        from: "5b77ea57adfc34053fd234f83e010a90596bfd5c0ef4630ef96631624ce22bc6",
        to: "7b84e2ddf555cdd057020ad35f700426f93d46490cfd00d223e3a1ccb0699681",
      },
    },
  },
  {
    recipe: "dependency-audit",
    from_version: "1.2.1",
    to_version: "1.2.2",
    bundles: {
      generic: {
        from: "b9eeb47c785de2baa219d1d79aa60781899f4bc62f2756ddbcbe7eea00d9d48d",
        to: "b8e58a3a19f6cb18b0ba740f30156f0e1c53fa08c686aff113f0078d1dfde203",
      },
      "claude-code": {
        from: "2d000c648777b29099af24e075d5c5ddbcc9f4449e2f0cecb7475c5d9daf51c7",
        to: "51b775a17fb75fe8fa5e9b16fd3d98ff6eb1bb27f107e782afce6dadc060b218",
      },
      codex: {
        from: "b0f7af55d5fc7e05a4f5c06d5427d47c70e06175468296989c6239a3eb90a587",
        to: "460b5e7137f0d7bfa9181fb1c002d9ae6d2102104b341edb9e500cac7b8cb19d",
      },
      cursor: {
        from: "f9ab5718921574c415fb7073a9dae864aeb35d7fb2198a59087c8300d6881e3d",
        to: "bf068292866a5b2604c1e18bb5940ec67677c8b6febcd8915a71e56c4cb24eb8",
      },
      "gemini-cli": {
        from: "dfca9d9bdf6569c9b119769494fe54f2c2f310bb561081d7f801d7e84366758d",
        to: "ba84d03359ed844131370fb1b21c27b8abbc8aa8d93f08e5866c09fa1f5f08bd",
      },
      opencode: {
        from: "1b49d2e665e9ff8540343b942b5499dafc341407bdcdfa9fc14a4a1cf35e8b30",
        to: "980c83e49a34256396397248c4c498add66f00d79a469fc203c4607eb18abab5",
      },
    },
  },
  {
    recipe: "document-api",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "bf5f7a140cf14efd8ad88b8ad86c75731b26e55eeae77b87278ad794c1ce067f",
        to: "2fd33a4a198e534ea97bef2478e278429bd145bd70de16eee814faab22fbfc4c",
      },
      "claude-code": {
        from: "5778e70b48a01fbfe5b851f62389fadb119186223c35f447e13c0f655adf99be",
        to: "18222f3a0e45970f3c20ef42e7285954db744d03bc8d693e03cba7fd39e15e22",
      },
      codex: {
        from: "1f205ced8c0cfe172b3e90526981b0fe2102717ac1c66f8f72c276de00c34256",
        to: "aeeeb4db3d79438ba9d18ba4e2ddef7967f1a3222ba1e0ba54db1ccb4d525ac4",
      },
      cursor: {
        from: "ad9e1f59d7d8b6498bb5e0c48ac84f8ff394a5eab2a3bc2f2258283f2a04b4b2",
        to: "4e6f233b57e938687f05882d49130146074638fcc403d4fdc9dd4ef9cc856f2d",
      },
      "gemini-cli": {
        from: "1054a7c7aa88f723dc179787d4d16bf1e787d1e08324a17b92153f16f4f547cd",
        to: "22487111b582355617f842f68d1bef576b4cfa17e671b69f0c9e2e9dbb46e1fd",
      },
      opencode: {
        from: "d44acbdd361a5fefe19494b7f9c9710124af4c7b13e9146e100bde209dadc74c",
        to: "9638c09d31ee505e8d831052a4d4ce3ee993bdf44a9cd0f3648829d856033d21",
      },
    },
  },
  {
    recipe: "generate-adr",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "bee917134f5f8f6b060dedc6f0889fea8bf8c307fd54bd259e44038f99d24760",
        to: "b8071dfe162ef26af6f12a62cc6c8c0d67bd061ea4319d2821928fa3b5089206",
      },
      "claude-code": {
        from: "1d7e891a430df5337320f7ece80f47947e87dfa546a8668176b1ca4e300d972d",
        to: "bdb652dfa45b8ba3daac7b31168c7d43be835dab56eb566d9a420fa29c2fc02e",
      },
      codex: {
        from: "823d4a70ed0c5c7cf0a0019e4540a08a1c1e0614e60405120466e69ba4ef2344",
        to: "ac0c109e21cda9a4c786ebbeb0201c18b58d827504f94432e330ffd4dc35eada",
      },
      cursor: {
        from: "cd4d190cd269748eeced0a2edc4a5ccea8359b8ebd14351999362ca5a6e1a5bb",
        to: "5b21e288b0aaf7a409230e678ac88df496752df1a6efd89c24b88c65dd3faa46",
      },
      "gemini-cli": {
        from: "f6d6cb1965e0a784968fba22537aa9c5493ac75c8c28391f3dc5bcbcc9213f03",
        to: "f962d68fc9a2728a5f72c4dc2c82d9da7fa13c6f544460a93dd57b8f0852d89c",
      },
      opencode: {
        from: "a1d04ee40e1659888d37b72ee2d200dc7e720283792dc163a19b9facc65a1c8a",
        to: "b22620fdbd35e9a088a7860efc12026c0059606c0544d381d00e78eee10ecd54",
      },
    },
  },
  {
    recipe: "generate-tests",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "4c8be0301d504e79275b23b29463e3b588dec533af78d7c7c6160651aabb9281",
        to: "8e514d22f38f496d9ca3d38e7ba1ae56e031fe88e36ccc401f73fdc955316d84",
      },
      "claude-code": {
        from: "753d444adb021a3c728ed0847dd339c055f8f79781f7efab4efb560cef3ac2cf",
        to: "d22429dff51e76b52ed83462abf1ef6e0144014480b4f1ba161d696481fbb006",
      },
      codex: {
        from: "810cb5b189b433846da1749bb333bb6b5b8a05b0e858d7fea0fece28db1c1eea",
        to: "a2713c52d740b8a32735739dd99763104cbc2c0d977f8257b95c491d9a58b368",
      },
      cursor: {
        from: "81e638f4ae2d87536defa60c005a4ca22e24e29d731cd49efdecc2181fb37fec",
        to: "94736113b46cb8b831d14665cbcc783d2173acef2fc78be0a5c859cd8a24813f",
      },
      "gemini-cli": {
        from: "da5d6e48f2a676deedac376a776939379b2d618f8179595789b943225ccdff44",
        to: "5047088328174cf8e4f7fbb56af49528c13c76dcd3b3da9199649c7ad458b1d5",
      },
      opencode: {
        from: "796accee31e70a23a406ea3ff8c5d085f38c624d423e34f60832f633de76d6ed",
        to: "ca5166cf9ed368031a1be7e53350f03893faf57376bb3a07d1503f1a2056ff66",
      },
    },
  },
  {
    recipe: "improve-type-safety",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "249b57fa32fd7a57b649891e9e086e28a117ae71cdc350229210dfa56eaa841a",
        to: "2d5390d5124059e0df0c0d01705a4224e1932138b711cc8617efb1dbbf7504e0",
      },
      "claude-code": {
        from: "63535644927674270aca87c49630587caf0bcc88fc17e6af7bdd07a2edcbe69f",
        to: "08c76485112600f2004b5cfa06e2a7ae1d83f0a90295e5ea6e3be13fcd1c76b1",
      },
      codex: {
        from: "28343a4897a8813a046ca5c7146f68b5f4dcf2eeef8644034c809e8d5ecfc43c",
        to: "2672569b63d91103175db8491059942c5cced7522adfc7c41a526829b7a15971",
      },
      cursor: {
        from: "d3be63a9fa685b5be28efedd8c418f9b59265d2186075f44675daf79cb4a7d44",
        to: "251e7071394c25af97b58404459f59e4eee7593dfa6e0d7334497c81dd51e4a2",
      },
      "gemini-cli": {
        from: "11d3adc992d0396af740d60efab00c1b9b7defe6071021e923d284f73fc6fae1",
        to: "e805430a2e1aa9d32a23af4d6dda051583a35c7d51963aa503059f953ddbc31c",
      },
      opencode: {
        from: "2952af2bbbbebbaccf9e75a82d523056307f42b6a0ed2d5b5c001708d0c35c26",
        to: "cba7836efc584fc9bee66abfde93d5b23518baf511c6e2e667338422854f1717",
      },
    },
  },
  {
    recipe: "incident-postmortem",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "1367ab1daeca53418d99a2e4957dcbf5c4cfa4dce2e9859c8ab4a518ad8a9c2d",
        to: "1d84e75c953f19217b7cffddb0dd0b559176ac5f927483a50832fb51c1c6afd3",
      },
      "claude-code": {
        from: "ff91ca54ec01fe38ce9c32612fdb88eabd45eca0f5681e75a6cb65059cb66485",
        to: "2a199985f92b8d55bef1a723085ff87674f3bf2dd90a36bb1b68afe78642eb6f",
      },
      codex: {
        from: "c2cf6a42513d9156d1a196a58e6df42268b42b1ed6b8e2441c629a39df22b552",
        to: "7b75140ea91dad51c7f8980441a450489867ba01f807ee8ae31333ef8e94b029",
      },
      cursor: {
        from: "7da9f31d92b5585661a8b9f35194aa9b8a806542fc74320215b2bf699ccca2de",
        to: "d893b9d5c54eaf67b16af16003d90687a1c2b7cd3af22e232fc1973896596386",
      },
      "gemini-cli": {
        from: "5027a23acfc73956f40b0c678a703c6a394ab7420476fc53325430263bc466a6",
        to: "957f2cbde9aa2b47d4ea65aa478004a4dd62c7515e0c5a594202711f41d4c3e3",
      },
      opencode: {
        from: "3acf15c8489f5d85b59d3136fab417606fb8d9f31f2f7d7449392b76184bbf74",
        to: "7e4a01b544053705452a34e0da78f58e4a19746883bca9b195a13fa48d1a8859",
      },
    },
  },
  {
    recipe: "migrate-framework",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "b3db1d0104177154aeba8c8f48e74fcaf4d02c99fdb3bb921b3217665f3faae1",
        to: "35dbdffaa6d229822617149db5acdf7f726c26bfb5c444c7b5830300206eba85",
      },
      "claude-code": {
        from: "f927faa407efdfd9291f0acad43fd060ad6909b72b1777a7e5de40ae3512a5e0",
        to: "b1f34dd66a59e4355bd99633130870a33ee5ff4139d010e625adbb2a25654a8d",
      },
      codex: {
        from: "308fe75561157b1c0ba0f237dedf1615c346751f859f7e7f819b09f79da1ebd5",
        to: "ad8ba4a61f8bb680e6acb8d5c80e10baa523d782db1c6436c374bce7d071329f",
      },
      cursor: {
        from: "e043aa7144db019aa53ef96991c39cb0035eb390238a45a1214f89af7337f115",
        to: "4edd008d09b6ab84c0a65c9db21e9efda408b3ecb4665f92fb6bed02c44e4d2c",
      },
      "gemini-cli": {
        from: "bb6260595213b8f4801b6e21481f8ba1add4972e3374fa50c3fcb292cbf05863",
        to: "7c43474fb8474f1153118c6b9ac2e98e9492790a00f6224898a82468b567efe6",
      },
      opencode: {
        from: "e9219199ade3157ef66b63ec997fdc6a0ed08f4049ff11aa2608d4d4d5810ba4",
        to: "8900f2e5ad8ce260dd852e61eac87d4e8a4938a5e5fa25a0b525ebb0121e1184",
      },
    },
  },
  {
    recipe: "profile-performance",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "aecd308d13211989c4c8713a2695f6d6e212a6c9e9d0d914260e4a6a1cb81aaf",
        to: "d0bf7acf45b15422f04d74aa3df188935429bcf5f80fe1d2f698a42e36439b18",
      },
      "claude-code": {
        from: "66d6c04d96db6d6300f4ee4cb67a6632dcf63b45b60d81a29465fb39f7d992d9",
        to: "08e90afde45ef263ca5d1f2cad4cec9ee931c2b659bc44a4bc4476925bb27805",
      },
      codex: {
        from: "182cc624ada74d88aafacdc622cd7a1f7c63341d4d1d2f76a24adbfdf08b3373",
        to: "30defac168cdd1a90b06f3b2fed34a78f6024fd161c169ee33ca62ac3bd5fc98",
      },
      cursor: {
        from: "1fd3461d2690dc24d033bad941bb98dfedb2c9f0b51d0e0760e05456e91c23cb",
        to: "38cd5de07fbb1c6a109829fdd9996d7ee3cacffca7994e69373ce3f319a6f0af",
      },
      "gemini-cli": {
        from: "bef8b487c8b1acb04364a082cc23e62adc7e626fb014c7bf5e0777dc60074746",
        to: "89d155b0edcaff1b0795fb972c6f888fde43c47c6cbdbb75bd3c5f0c6912b97d",
      },
      opencode: {
        from: "0416d578a2e3ab4b2cd41b49cc02e255caf2314c16f1038e4b0a3319352ab5e0",
        to: "15f32c08ba336a6a10218c67271aef24e291d5f6e80bd745daea95c5e36de5f4",
      },
    },
  },
  {
    recipe: "refactor-large-module",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "2594af80a5eff885f0b699ff784b736ed0570304b862dd57391ae110f9c5a827",
        to: "202748b60ef95a4dd4dd4f7c4fc693083ef278bd8f349d33230bd05babd15fbf",
      },
      "claude-code": {
        from: "86ea89f6ddb0f6a05eeb661ddc566b059c9f93ea7e49aa49424397e384f156e2",
        to: "a8c772e12b51a89cb7545c492ec751856a380cae9e05ba01e6289bcb33f0d680",
      },
      codex: {
        from: "934e8d2c1588ad6d98ef339b8949159bc04064e36565984c466070f029cb14af",
        to: "fcd0cd7ee1fc702d7c5a6fa489cdc58b4b2a691545902a79a6f65b0e50b246f6",
      },
      cursor: {
        from: "7db3cefda83ab5be78260145aeacaac7c763dd5f6254df9188683ddfd32ac1e0",
        to: "303547af377d2b46270948b3313f7478d7931d741f964c0a65fb7b40b748e2f5",
      },
      "gemini-cli": {
        from: "d68d08703e16aa33f35a7376c4fab370e32ee820a0ffbde576d155150b5f9ae6",
        to: "a15543d80118ac0fd91378aa83e3524d0ea02a4622d4d841b436c31ca667a015",
      },
      opencode: {
        from: "778886fb6d3a83ed3ce57b6a452d94c71e51604957133514530264d824773ea0",
        to: "a91561118d65ae81ac3892273c635ba3e94681ac47f7eb0fbeb0c1353a89bec3",
      },
    },
  },
  {
    recipe: "reproduce-bug",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "f49cc6c04f15ab00165ccc15bcc022a0ffeb5de83ed9383d05dd99cb9754707e",
        to: "1546faaf565e29a8d439d1bf73e0f6329769cbe6393c54f4b712c41cd24d852f",
      },
      "claude-code": {
        from: "3752f0ad17782b4d5bfe5f40df0eda0aef63f5dd707608175b024061bc2b5272",
        to: "7354a433723c93c145d2ace1d611ba1a19eadcbd9f319034fa9c3ff08ca1cee1",
      },
      codex: {
        from: "b2c1a27fa1721ca24f1ebb0f638f152a6e4cf39cc3369cd4dcd6f5477fe2fb58",
        to: "e2f968ec5a4b880afb2ef3df8e044a93f18530b68a3756483770f01e8e21cb86",
      },
      cursor: {
        from: "3145eeaec14fdc016bf7e6b03d70dabec5f48bc33e87044e18d4ad375782cb0d",
        to: "39c6fffd9f1322c0f6ea3736fa485115b7d60ee3b2f662578ccf1333248bcf2f",
      },
      "gemini-cli": {
        from: "b59bec791cd0498f092bedff63bfcfc7cc99101a9224204a29bdd49be6ff68cf",
        to: "8eeb487de21dc5a9024e43dff9e3acbcb133be7aa9edec690ea319b4fe0aeab2",
      },
      opencode: {
        from: "c77fc62ac5f8824593d31b20dd87cc665d23c67f2d8418dbc80331f447abfc45",
        to: "12e79e1b178d65d5d9556b567cae38b92737aa33725d708fde03025c524eb5b1",
      },
    },
  },
  {
    recipe: "review-pull-request",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "991c92c6f6a9ef1ee631b0e26976d2e4e84fcafe70a685e73c22c1fc242714d8",
        to: "b3b90eca13f3b0eff208e5488be7967fe6b8ef0f4c9f24566ecaeddf80d1b415",
      },
      "claude-code": {
        from: "72a016ec06737e56b19aa98136133882bd27996f7ba02ef83824a2b11b2faf57",
        to: "c2d4399787c399cdd064041bc5bf3041e48680dd91e2153456e0d21d4e42b373",
      },
      codex: {
        from: "6c65a71efeda74ac38051395e9dfc6d9ef1076d20b006a18a1277d233d28bd27",
        to: "2b8e5ab83b8033fdc96d174c0c37159fac3b77ae846f02491e98ec45e243de4b",
      },
      cursor: {
        from: "0f6bb4b6906d21c67e4236ec12612ffc1e4df8a16fde24fda0a02db476ca6262",
        to: "0227cee1be7a828e1616f4d6d806b9f63d95f51b63ec9a7f97667af54d252436",
      },
      "gemini-cli": {
        from: "33050f0865c1f1c56f42077be1394a37fd484eb97bffb17984a75cf3a155f824",
        to: "a1b9ad668097567422756e5c617b449b17a741bb93925647170f23c25ba67352",
      },
      opencode: {
        from: "d59280ba52a526c7df66bf163b00b5f738e4d156c7b34d89074f7deae92e28e3",
        to: "56b2e9acbebd8da873d29c5e1dcc33ee69d672cc3f17fc008d22dc7b3f446de9",
      },
    },
  },
  {
    recipe: "security-review",
    from_version: "1.2.1",
    to_version: "1.2.2",
    bundles: {
      generic: {
        from: "0af9be46939a72c805352586a1c5c0ed040189db2b68594e9a87031679e5c590",
        to: "8f11d7a0fec466efd62e0c5164f60c874fc0f8dce34b7a82ca4db50cf8a86658",
      },
      "claude-code": {
        from: "81a54dc8c3cd84cc8f04d3a7228326a8c46086e326894c72c3e563792c39df71",
        to: "7450e0b5bc124ff3eaad35e523ef3c6b2a6385cf244695c5324ad0fd3474badf",
      },
      codex: {
        from: "a9e7378cc815c66b9e9fe921567b1d1903c8fb9dd2c5719db049c69f99ec9406",
        to: "c82460ab495024ccab55e84f1298d2709b58463ec4fb05be4da2979ff6eda2bc",
      },
      cursor: {
        from: "ce545d7bc0538732761900eb02aa45187939b9ae7310791bf2c446ec42bab198",
        to: "0502a1a9a4886edaaa5e6b0be7731a3aa8379d4cddbb3b6f8d6e2f2d50b528f1",
      },
      "gemini-cli": {
        from: "08f7d7f3f7a936b7c453bc002358d27bdd3868b6cc848d870e0ece0984f85f5f",
        to: "48a613b52fef1fab0bad6faee3acf2971d174448dbfeec57da1091454f57ad40",
      },
      opencode: {
        from: "6aa01de68169943344346687398623afa13b217b6776dfd628313c254f2a37c2",
        to: "abfa86df7beb48ffcc98224c714c04c77df3a154a6c4231373e8674824dfcf68",
      },
    },
  },
  {
    recipe: "synchronize-documentation",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "426ed65d3dcf5aaa94ea5f203580252f26b4d8dfdda249b208aa68479b157faf",
        to: "dfa5e948f00b20cf80df5091efeda22ea78d3e0af26d251238092cd84f709956",
      },
      "claude-code": {
        from: "fcd23567e938ed827ec1abce1e5ed4aa90bc1abbf84ba90683e187d7eec2c38d",
        to: "1e90dc7c428a36fbbf62c6453d8890b556a0855540a85b180010b82de240d8d9",
      },
      codex: {
        from: "9a604aa3bcaf9d5e223580cefbbcde70cc7222e950abb8cfe06d5e0c50f9e84c",
        to: "a006a25a59f08fcd5529d36134d596435e9b14d451ce3dc19bb8f06f0007ddfd",
      },
      cursor: {
        from: "302334e965e49d942db89a96ca65c6bed01af91e21e7a0ccdddad68655824792",
        to: "2e7f045970804f0d12e79867760ff6215a1c5af56d70f18c8c8c02efd18134e3",
      },
      "gemini-cli": {
        from: "c1ddbbf7a358bbe0eb108d61a05048b4d8ab453ba912b2b2e3b3dbdbdfedd95b",
        to: "77310181add7d522dfa65d3f57f502b5d166054cd4468b06aac709a00eee7d9e",
      },
      opencode: {
        from: "d226884a5fa395fd103fd2f1c771a0d759c543bd58a830750638eb165de15e1b",
        to: "b17df394ca5a171b9ef72576354bf17b5fbc68923b3dd7df46df232db7ede6af",
      },
    },
  },
  {
    recipe: "triage-issues",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "1a86080ab18d849dd936e60a78bfd0f898ba14721525d1be3054a027e004b0af",
        to: "e07a88ab29ef55d300d3f0ffc24f0944744311acf8d228772dccdaf230cf8177",
      },
      "claude-code": {
        from: "e3c5781ee496d5770d03c0f2663ec2edf5c8880a38f02e25621bab94c452b9c5",
        to: "86364bb90a5288945cd02ddc03a54c0f3d60699f347d76b60eb235e0647bc254",
      },
      codex: {
        from: "8e1f8fc01595d25360d3cd167329a9bcef6f018b56661baa081d388cdd154c4e",
        to: "88b6e4e0ea99af22b6420620ba1e8f844129a4b990d3731bfdf11585f86caf50",
      },
      cursor: {
        from: "89c172c1c6158a71270d9e09b0376c32d05ae36d4662a3ee2da7425e1b354823",
        to: "581001070ce4e953150bd9d286eb58a961c46f531ba1990b795b1cf421b5301d",
      },
      "gemini-cli": {
        from: "423f3018127290cfb4ff64b7431c7e4154395642519bcdc6503724b593dfc840",
        to: "ad4d15af39c02a95c74c649a3a962d474e45ba345a5b003a74c9517c53152855",
      },
      opencode: {
        from: "5ca114546cc5e821e0bf891097bb1022169a1091953e988e568f2a493be74766",
        to: "4360d026f86742c0e6a64c154d54f9ce42081ea4be0cc90e21e881f3c1ee2801",
      },
    },
  },
  {
    recipe: "upgrade-dependencies",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "c34ed8ee725774ecf96db03986b9ecd9c2ad0093c348390bbfb852293dd16dbc",
        to: "4b01b201655b79afec41f1aba6f55b5aa35bd76f6c0cf480aaf66e98d829ed77",
      },
      "claude-code": {
        from: "40d880cc7a79b85af8c98debcfae5f816f949bcd82ffef8be5af65c1757357b4",
        to: "6526b857d37a90e2816801ddb0825ac5f1b4dae5b83ff3ef9aa8055d116be8d8",
      },
      codex: {
        from: "e3c25da2a17eb350f28b4500f7ea9d1405284b48402ebd4679a269863945e238",
        to: "b1c4ee57db0dccc40ae9f9ee401ac17f21a6bc7a18795acbdce201cbeba97f44",
      },
      cursor: {
        from: "ea04bfdafd18deef973a637ef680b9efcab16f8d2dedf6e2ace43150840c2e6c",
        to: "7f3715f97c9fb5d41102be9bd282eb5d44c90320e07bd5bf83c4597fb42794eb",
      },
      "gemini-cli": {
        from: "cef37e510f1cbe2160552c05669596d0d0100e7d6d5d9e55b3111fd625dfb104",
        to: "00c9b3428f05603724f2b937a969c5733830a874b8d7eeec34f19706098398d8",
      },
      opencode: {
        from: "e85afba03afba0c8accc89e6b0fa0e0f6c92fbe55d193ce3761f327555f2fecc",
        to: "146be0d024c1758dfa2c23cd92aea692a5e54f4f75fe69f421508d2f7402f234",
      },
    },
  },
  {
    recipe: "write-release-notes",
    from_version: "1.2.0",
    to_version: "1.2.1",
    bundles: {
      generic: {
        from: "30d4652cf6dd4fdc600ef1f23acbec2fa7cc148d258dddb4c7c2acde4eb016d9",
        to: "6a2edfc60a38f0789ddc21775a6e08f5ab195104fb3cbd7abf71e78ac43a4282",
      },
      "claude-code": {
        from: "9d1d49e8394b4a6d68d1f821ba39e133909cdc5025f418c22aab71d8909999bc",
        to: "d14a1413bc1b3f9308fa9375856df4478802921dd9403ac9774f090428984004",
      },
      codex: {
        from: "ee5557e15994e6693de68dcd063ebebbe0ba76bdd90b9ed75ecd87a01b9c498b",
        to: "3046b7f7c931c54141ea37433be5b394d3155feb0dc3c04831eb0b3ef8d92a7d",
      },
      cursor: {
        from: "54d26fe7dddd5e1b262b0c6bc18b93706fdef575272fd24d0ceceec5513ac756",
        to: "9b5f2dff447c2b77945b904a8d4b6d05222b7f6bad1832a2984935dd2102c1fe",
      },
      "gemini-cli": {
        from: "0ecd3b62d00be80f522bbe3f4f5e12a8bf8e165f3bc8fd53cf74b1fcebb63795",
        to: "9d15b7231f653165c661fc29b0d55ec9db732b2f9b251e27b848d006932e3023",
      },
      opencode: {
        from: "df5c72abda9dae255794e41fbc4edcdd7a0e8c5e9b9116e46a57e5ccaf9162f2",
        to: "ac3a6489aa4c7eac8f279bd505d61fe215883c8b342dbb36e416864126840b6a",
      },
    },
  },
] as const satisfies readonly RetainedV2Migration[];
